# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :app do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  	gradle(
  		task: "app:assembleRelease"
  	)

  end

#  lane :app_deploy do
#
#  	upload_to_play_store(
#        track: 'alpha',
#        rollout: '1',
#        skip_upload_metadata: true,
#        skip_upload_images: true,
#        skip_upload_screenshots: true,
#        apk: '/home/circleci/workspace/app/build/outputs/apk/release/app-release.apk',
#        mapping: '/home/circleci/workspace/app/build/outputs/mapping/release/mapping.txt'
#    )
#
#  end

  lane :increment_version do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  end

end