# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :app do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  	gradle(
  		task: "app:assembleRelease"
  	)

  	upload_to_play_store(
        track: 'alpha',
        rollout: '1'
    )

  end

  lane :increment_version do

  	increment_version_code(
  		gradle_file_path: "version.properties"
  	)

  end

end