# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

#  lane :app do
#
#  	increment_version_code(
#  		gradle_file_path: "version.properties"
#  	)
#
#  	gradle(
#  		task: "app:assembleRelease"
#  	)
#
#  end

  lane :app_deploy do

  	upload_to_play_store(
        track: 'internal',
        rollout: '1',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_apk: true,
        skip_upload_screenshots: true,
        json_key: ENV["INTERNAL_JSON_KEY"],
    )

  end

#  lane :increment_version do
#
#  	increment_version_code(
#  		gradle_file_path: "version.properties"
#  	)
#
#  end

end